// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/nkiryanov/go-metrics/internal/models"
)

// CollectorMock is a mock implementation of collector.Collector.
//
//	func TestSomethingThatUsesCollector(t *testing.T) {
//
//		// make and configure a mocked collector.Collector
//		mockedCollector := &CollectorMock{
//			CollectFunc: func(ctx context.Context) error {
//				panic("mock out the Collect method")
//			},
//			ListFunc: func() []models.Metric {
//				panic("mock out the List method")
//			},
//		}
//
//		// use mockedCollector in code that requires collector.Collector
//		// and then make assertions.
//
//	}
type CollectorMock struct {
	// CollectFunc mocks the Collect method.
	CollectFunc func(ctx context.Context) error

	// ListFunc mocks the List method.
	ListFunc func() []models.Metric

	// calls tracks calls to the methods.
	calls struct {
		// Collect holds details about calls to the Collect method.
		Collect []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// List holds details about calls to the List method.
		List []struct {
		}
	}
	lockCollect sync.RWMutex
	lockList    sync.RWMutex
}

// Collect calls CollectFunc.
func (mock *CollectorMock) Collect(ctx context.Context) error {
	if mock.CollectFunc == nil {
		panic("CollectorMock.CollectFunc: method is nil but Collector.Collect was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCollect.Lock()
	mock.calls.Collect = append(mock.calls.Collect, callInfo)
	mock.lockCollect.Unlock()
	return mock.CollectFunc(ctx)
}

// CollectCalls gets all the calls that were made to Collect.
// Check the length with:
//
//	len(mockedCollector.CollectCalls())
func (mock *CollectorMock) CollectCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCollect.RLock()
	calls = mock.calls.Collect
	mock.lockCollect.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *CollectorMock) List() []models.Metric {
	if mock.ListFunc == nil {
		panic("CollectorMock.ListFunc: method is nil but Collector.List was just called")
	}
	callInfo := struct {
	}{}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc()
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedCollector.ListCalls())
func (mock *CollectorMock) ListCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}
