// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/nkiryanov/go-metrics/internal/logger"
)

// LoggerMock is a mock implementation of logger.Logger.
//
//	func TestSomethingThatUsesLogger(t *testing.T) {
//
//		// make and configure a mocked logger.Logger
//		mockedLogger := &LoggerMock{
//			DebugFunc: func(msg string, args ...any)  {
//				panic("mock out the Debug method")
//			},
//			ErrorFunc: func(msg string, args ...any)  {
//				panic("mock out the Error method")
//			},
//			InfoFunc: func(msg string, args ...any)  {
//				panic("mock out the Info method")
//			},
//			WarnFunc: func(msg string, args ...any)  {
//				panic("mock out the Warn method")
//			},
//			WithFunc: func(args ...any) logger.Logger {
//				panic("mock out the With method")
//			},
//			WithGroupFunc: func(name string) logger.Logger {
//				panic("mock out the WithGroup method")
//			},
//		}
//
//		// use mockedLogger in code that requires logger.Logger
//		// and then make assertions.
//
//	}
type LoggerMock struct {
	// DebugFunc mocks the Debug method.
	DebugFunc func(msg string, args ...any)

	// ErrorFunc mocks the Error method.
	ErrorFunc func(msg string, args ...any)

	// InfoFunc mocks the Info method.
	InfoFunc func(msg string, args ...any)

	// WarnFunc mocks the Warn method.
	WarnFunc func(msg string, args ...any)

	// WithFunc mocks the With method.
	WithFunc func(args ...any) logger.Logger

	// WithGroupFunc mocks the WithGroup method.
	WithGroupFunc func(name string) logger.Logger

	// calls tracks calls to the methods.
	calls struct {
		// Debug holds details about calls to the Debug method.
		Debug []struct {
			// Msg is the msg argument value.
			Msg string
			// Args is the args argument value.
			Args []any
		}
		// Error holds details about calls to the Error method.
		Error []struct {
			// Msg is the msg argument value.
			Msg string
			// Args is the args argument value.
			Args []any
		}
		// Info holds details about calls to the Info method.
		Info []struct {
			// Msg is the msg argument value.
			Msg string
			// Args is the args argument value.
			Args []any
		}
		// Warn holds details about calls to the Warn method.
		Warn []struct {
			// Msg is the msg argument value.
			Msg string
			// Args is the args argument value.
			Args []any
		}
		// With holds details about calls to the With method.
		With []struct {
			// Args is the args argument value.
			Args []any
		}
		// WithGroup holds details about calls to the WithGroup method.
		WithGroup []struct {
			// Name is the name argument value.
			Name string
		}
	}
	lockDebug     sync.RWMutex
	lockError     sync.RWMutex
	lockInfo      sync.RWMutex
	lockWarn      sync.RWMutex
	lockWith      sync.RWMutex
	lockWithGroup sync.RWMutex
}

// Debug calls DebugFunc.
func (mock *LoggerMock) Debug(msg string, args ...any) {
	if mock.DebugFunc == nil {
		panic("LoggerMock.DebugFunc: method is nil but Logger.Debug was just called")
	}
	callInfo := struct {
		Msg  string
		Args []any
	}{
		Msg:  msg,
		Args: args,
	}
	mock.lockDebug.Lock()
	mock.calls.Debug = append(mock.calls.Debug, callInfo)
	mock.lockDebug.Unlock()
	mock.DebugFunc(msg, args...)
}

// DebugCalls gets all the calls that were made to Debug.
// Check the length with:
//
//	len(mockedLogger.DebugCalls())
func (mock *LoggerMock) DebugCalls() []struct {
	Msg  string
	Args []any
} {
	var calls []struct {
		Msg  string
		Args []any
	}
	mock.lockDebug.RLock()
	calls = mock.calls.Debug
	mock.lockDebug.RUnlock()
	return calls
}

// Error calls ErrorFunc.
func (mock *LoggerMock) Error(msg string, args ...any) {
	if mock.ErrorFunc == nil {
		panic("LoggerMock.ErrorFunc: method is nil but Logger.Error was just called")
	}
	callInfo := struct {
		Msg  string
		Args []any
	}{
		Msg:  msg,
		Args: args,
	}
	mock.lockError.Lock()
	mock.calls.Error = append(mock.calls.Error, callInfo)
	mock.lockError.Unlock()
	mock.ErrorFunc(msg, args...)
}

// ErrorCalls gets all the calls that were made to Error.
// Check the length with:
//
//	len(mockedLogger.ErrorCalls())
func (mock *LoggerMock) ErrorCalls() []struct {
	Msg  string
	Args []any
} {
	var calls []struct {
		Msg  string
		Args []any
	}
	mock.lockError.RLock()
	calls = mock.calls.Error
	mock.lockError.RUnlock()
	return calls
}

// Info calls InfoFunc.
func (mock *LoggerMock) Info(msg string, args ...any) {
	if mock.InfoFunc == nil {
		panic("LoggerMock.InfoFunc: method is nil but Logger.Info was just called")
	}
	callInfo := struct {
		Msg  string
		Args []any
	}{
		Msg:  msg,
		Args: args,
	}
	mock.lockInfo.Lock()
	mock.calls.Info = append(mock.calls.Info, callInfo)
	mock.lockInfo.Unlock()
	mock.InfoFunc(msg, args...)
}

// InfoCalls gets all the calls that were made to Info.
// Check the length with:
//
//	len(mockedLogger.InfoCalls())
func (mock *LoggerMock) InfoCalls() []struct {
	Msg  string
	Args []any
} {
	var calls []struct {
		Msg  string
		Args []any
	}
	mock.lockInfo.RLock()
	calls = mock.calls.Info
	mock.lockInfo.RUnlock()
	return calls
}

// Warn calls WarnFunc.
func (mock *LoggerMock) Warn(msg string, args ...any) {
	if mock.WarnFunc == nil {
		panic("LoggerMock.WarnFunc: method is nil but Logger.Warn was just called")
	}
	callInfo := struct {
		Msg  string
		Args []any
	}{
		Msg:  msg,
		Args: args,
	}
	mock.lockWarn.Lock()
	mock.calls.Warn = append(mock.calls.Warn, callInfo)
	mock.lockWarn.Unlock()
	mock.WarnFunc(msg, args...)
}

// WarnCalls gets all the calls that were made to Warn.
// Check the length with:
//
//	len(mockedLogger.WarnCalls())
func (mock *LoggerMock) WarnCalls() []struct {
	Msg  string
	Args []any
} {
	var calls []struct {
		Msg  string
		Args []any
	}
	mock.lockWarn.RLock()
	calls = mock.calls.Warn
	mock.lockWarn.RUnlock()
	return calls
}

// With calls WithFunc.
func (mock *LoggerMock) With(args ...any) logger.Logger {
	if mock.WithFunc == nil {
		panic("LoggerMock.WithFunc: method is nil but Logger.With was just called")
	}
	callInfo := struct {
		Args []any
	}{
		Args: args,
	}
	mock.lockWith.Lock()
	mock.calls.With = append(mock.calls.With, callInfo)
	mock.lockWith.Unlock()
	return mock.WithFunc(args...)
}

// WithCalls gets all the calls that were made to With.
// Check the length with:
//
//	len(mockedLogger.WithCalls())
func (mock *LoggerMock) WithCalls() []struct {
	Args []any
} {
	var calls []struct {
		Args []any
	}
	mock.lockWith.RLock()
	calls = mock.calls.With
	mock.lockWith.RUnlock()
	return calls
}

// WithGroup calls WithGroupFunc.
func (mock *LoggerMock) WithGroup(name string) logger.Logger {
	if mock.WithGroupFunc == nil {
		panic("LoggerMock.WithGroupFunc: method is nil but Logger.WithGroup was just called")
	}
	callInfo := struct {
		Name string
	}{
		Name: name,
	}
	mock.lockWithGroup.Lock()
	mock.calls.WithGroup = append(mock.calls.WithGroup, callInfo)
	mock.lockWithGroup.Unlock()
	return mock.WithGroupFunc(name)
}

// WithGroupCalls gets all the calls that were made to WithGroup.
// Check the length with:
//
//	len(mockedLogger.WithGroupCalls())
func (mock *LoggerMock) WithGroupCalls() []struct {
	Name string
} {
	var calls []struct {
		Name string
	}
	mock.lockWithGroup.RLock()
	calls = mock.calls.WithGroup
	mock.lockWithGroup.RUnlock()
	return calls
}
