// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/nkiryanov/go-metrics/internal/agent/capturer"
	"github.com/nkiryanov/go-metrics/internal/storage"
)

// CapturerMock is a mock implementation of capturer.Capturer.
//
//	func TestSomethingThatUsesCapturer(t *testing.T) {
//
//		// make and configure a mocked capturer.Capturer
//		mockedCapturer := &CapturerMock{
//			CaptureFunc: func() []capturer.Stat {
//				panic("mock out the Capture method")
//			},
//			CaptureWithSaveFunc: func(s storage.Storage) error {
//				panic("mock out the CaptureWithSave method")
//			},
//		}
//
//		// use mockedCapturer in code that requires capturer.Capturer
//		// and then make assertions.
//
//	}
type CapturerMock struct {
	// CaptureFunc mocks the Capture method.
	CaptureFunc func() []capturer.Stat

	// CaptureWithSaveFunc mocks the CaptureWithSave method.
	CaptureWithSaveFunc func(s storage.Storage) error

	// calls tracks calls to the methods.
	calls struct {
		// Capture holds details about calls to the Capture method.
		Capture []struct {
		}
		// CaptureWithSave holds details about calls to the CaptureWithSave method.
		CaptureWithSave []struct {
			// S is the s argument value.
			S storage.Storage
		}
	}
	lockCapture         sync.RWMutex
	lockCaptureWithSave sync.RWMutex
}

// Capture calls CaptureFunc.
func (mock *CapturerMock) Capture() []capturer.Stat {
	if mock.CaptureFunc == nil {
		panic("CapturerMock.CaptureFunc: method is nil but Capturer.Capture was just called")
	}
	callInfo := struct {
	}{}
	mock.lockCapture.Lock()
	mock.calls.Capture = append(mock.calls.Capture, callInfo)
	mock.lockCapture.Unlock()
	return mock.CaptureFunc()
}

// CaptureCalls gets all the calls that were made to Capture.
// Check the length with:
//
//	len(mockedCapturer.CaptureCalls())
func (mock *CapturerMock) CaptureCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCapture.RLock()
	calls = mock.calls.Capture
	mock.lockCapture.RUnlock()
	return calls
}

// CaptureWithSave calls CaptureWithSaveFunc.
func (mock *CapturerMock) CaptureWithSave(s storage.Storage) error {
	if mock.CaptureWithSaveFunc == nil {
		panic("CapturerMock.CaptureWithSaveFunc: method is nil but Capturer.CaptureWithSave was just called")
	}
	callInfo := struct {
		S storage.Storage
	}{
		S: s,
	}
	mock.lockCaptureWithSave.Lock()
	mock.calls.CaptureWithSave = append(mock.calls.CaptureWithSave, callInfo)
	mock.lockCaptureWithSave.Unlock()
	return mock.CaptureWithSaveFunc(s)
}

// CaptureWithSaveCalls gets all the calls that were made to CaptureWithSave.
// Check the length with:
//
//	len(mockedCapturer.CaptureWithSaveCalls())
func (mock *CapturerMock) CaptureWithSaveCalls() []struct {
	S storage.Storage
} {
	var calls []struct {
		S storage.Storage
	}
	mock.lockCaptureWithSave.RLock()
	calls = mock.calls.CaptureWithSave
	mock.lockCaptureWithSave.RUnlock()
	return calls
}
