// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/nkiryanov/go-metrics/internal/agent/capturer"
	"github.com/nkiryanov/go-metrics/internal/storage"
)

// CapturerMock is a mock implementation of capturer.Capturer.
//
//	func TestSomethingThatUsesCapturer(t *testing.T) {
//
//		// make and configure a mocked capturer.Capturer
//		mockedCapturer := &CapturerMock{
//			CaptureFunc: func() []capturer.Stat {
//				panic("mock out the Capture method")
//			},
//			CaptureAndSaveFunc: func(s storage.Storage) error {
//				panic("mock out the CaptureAndSave method")
//			},
//		}
//
//		// use mockedCapturer in code that requires capturer.Capturer
//		// and then make assertions.
//
//	}
type CapturerMock struct {
	// CaptureFunc mocks the Capture method.
	CaptureFunc func() []capturer.Stat

	// CaptureAndSaveFunc mocks the CaptureAndSave method.
	CaptureAndSaveFunc func(s storage.Storage) error

	// calls tracks calls to the methods.
	calls struct {
		// Capture holds details about calls to the Capture method.
		Capture []struct {
		}
		// CaptureAndSave holds details about calls to the CaptureAndSave method.
		CaptureAndSave []struct {
			// S is the s argument value.
			S storage.Storage
		}
	}
	lockCapture        sync.RWMutex
	lockCaptureAndSave sync.RWMutex
}

// Capture calls CaptureFunc.
func (mock *CapturerMock) Capture() []capturer.Stat {
	if mock.CaptureFunc == nil {
		panic("CapturerMock.CaptureFunc: method is nil but Capturer.Capture was just called")
	}
	callInfo := struct {
	}{}
	mock.lockCapture.Lock()
	mock.calls.Capture = append(mock.calls.Capture, callInfo)
	mock.lockCapture.Unlock()
	return mock.CaptureFunc()
}

// CaptureCalls gets all the calls that were made to Capture.
// Check the length with:
//
//	len(mockedCapturer.CaptureCalls())
func (mock *CapturerMock) CaptureCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCapture.RLock()
	calls = mock.calls.Capture
	mock.lockCapture.RUnlock()
	return calls
}

// CaptureAndSave calls CaptureAndSaveFunc.
func (mock *CapturerMock) CaptureAndSave(s storage.Storage) error {
	if mock.CaptureAndSaveFunc == nil {
		panic("CapturerMock.CaptureAndSaveFunc: method is nil but Capturer.CaptureAndSave was just called")
	}
	callInfo := struct {
		S storage.Storage
	}{
		S: s,
	}
	mock.lockCaptureAndSave.Lock()
	mock.calls.CaptureAndSave = append(mock.calls.CaptureAndSave, callInfo)
	mock.lockCaptureAndSave.Unlock()
	return mock.CaptureAndSaveFunc(s)
}

// CaptureAndSaveCalls gets all the calls that were made to CaptureAndSave.
// Check the length with:
//
//	len(mockedCapturer.CaptureAndSaveCalls())
func (mock *CapturerMock) CaptureAndSaveCalls() []struct {
	S storage.Storage
} {
	var calls []struct {
		S storage.Storage
	}
	mock.lockCaptureAndSave.RLock()
	calls = mock.calls.CaptureAndSave
	mock.lockCaptureAndSave.RUnlock()
	return calls
}
