// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/nkiryanov/go-metrics/internal/models"
)

// ReporterMock is a mock implementation of reporter.Reporter.
//
//	func TestSomethingThatUsesReporter(t *testing.T) {
//
//		// make and configure a mocked reporter.Reporter
//		mockedReporter := &ReporterMock{
//			ReportBatchFunc: func(metrics []models.Metric) error {
//				panic("mock out the ReportBatch method")
//			},
//			ReportOnceFunc: func(metric models.Metric) error {
//				panic("mock out the ReportOnce method")
//			},
//		}
//
//		// use mockedReporter in code that requires reporter.Reporter
//		// and then make assertions.
//
//	}
type ReporterMock struct {
	// ReportBatchFunc mocks the ReportBatch method.
	ReportBatchFunc func(metrics []models.Metric) error

	// ReportOnceFunc mocks the ReportOnce method.
	ReportOnceFunc func(metric models.Metric) error

	// calls tracks calls to the methods.
	calls struct {
		// ReportBatch holds details about calls to the ReportBatch method.
		ReportBatch []struct {
			// Metrics is the metrics argument value.
			Metrics []models.Metric
		}
		// ReportOnce holds details about calls to the ReportOnce method.
		ReportOnce []struct {
			// Metric is the metric argument value.
			Metric models.Metric
		}
	}
	lockReportBatch sync.RWMutex
	lockReportOnce  sync.RWMutex
}

// ReportBatch calls ReportBatchFunc.
func (mock *ReporterMock) ReportBatch(metrics []models.Metric) error {
	if mock.ReportBatchFunc == nil {
		panic("ReporterMock.ReportBatchFunc: method is nil but Reporter.ReportBatch was just called")
	}
	callInfo := struct {
		Metrics []models.Metric
	}{
		Metrics: metrics,
	}
	mock.lockReportBatch.Lock()
	mock.calls.ReportBatch = append(mock.calls.ReportBatch, callInfo)
	mock.lockReportBatch.Unlock()
	return mock.ReportBatchFunc(metrics)
}

// ReportBatchCalls gets all the calls that were made to ReportBatch.
// Check the length with:
//
//	len(mockedReporter.ReportBatchCalls())
func (mock *ReporterMock) ReportBatchCalls() []struct {
	Metrics []models.Metric
} {
	var calls []struct {
		Metrics []models.Metric
	}
	mock.lockReportBatch.RLock()
	calls = mock.calls.ReportBatch
	mock.lockReportBatch.RUnlock()
	return calls
}

// ReportOnce calls ReportOnceFunc.
func (mock *ReporterMock) ReportOnce(metric models.Metric) error {
	if mock.ReportOnceFunc == nil {
		panic("ReporterMock.ReportOnceFunc: method is nil but Reporter.ReportOnce was just called")
	}
	callInfo := struct {
		Metric models.Metric
	}{
		Metric: metric,
	}
	mock.lockReportOnce.Lock()
	mock.calls.ReportOnce = append(mock.calls.ReportOnce, callInfo)
	mock.lockReportOnce.Unlock()
	return mock.ReportOnceFunc(metric)
}

// ReportOnceCalls gets all the calls that were made to ReportOnce.
// Check the length with:
//
//	len(mockedReporter.ReportOnceCalls())
func (mock *ReporterMock) ReportOnceCalls() []struct {
	Metric models.Metric
} {
	var calls []struct {
		Metric models.Metric
	}
	mock.lockReportOnce.RLock()
	calls = mock.calls.ReportOnce
	mock.lockReportOnce.RUnlock()
	return calls
}
