// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/nkiryanov/go-metrics/internal/agent/reporter"
)

// ReporterMock is a mock implementation of reporter.Reporter.
//
//	func TestSomethingThatUsesReporter(t *testing.T) {
//
//		// make and configure a mocked reporter.Reporter
//		mockedReporter := &ReporterMock{
//			ReportBatchFunc: func(ms []*reporter.Metric) []error {
//				panic("mock out the ReportBatch method")
//			},
//			ReportOnceFunc: func(m *reporter.Metric) error {
//				panic("mock out the ReportOnce method")
//			},
//		}
//
//		// use mockedReporter in code that requires reporter.Reporter
//		// and then make assertions.
//
//	}
type ReporterMock struct {
	// ReportBatchFunc mocks the ReportBatch method.
	ReportBatchFunc func(ms []*reporter.Metric) []error

	// ReportOnceFunc mocks the ReportOnce method.
	ReportOnceFunc func(m *reporter.Metric) error

	// calls tracks calls to the methods.
	calls struct {
		// ReportBatch holds details about calls to the ReportBatch method.
		ReportBatch []struct {
			// Ms is the ms argument value.
			Ms []*reporter.Metric
		}
		// ReportOnce holds details about calls to the ReportOnce method.
		ReportOnce []struct {
			// M is the m argument value.
			M *reporter.Metric
		}
	}
	lockReportBatch sync.RWMutex
	lockReportOnce  sync.RWMutex
}

// ReportBatch calls ReportBatchFunc.
func (mock *ReporterMock) ReportBatch(ms []*reporter.Metric) []error {
	if mock.ReportBatchFunc == nil {
		panic("ReporterMock.ReportBatchFunc: method is nil but Reporter.ReportBatch was just called")
	}
	callInfo := struct {
		Ms []*reporter.Metric
	}{
		Ms: ms,
	}
	mock.lockReportBatch.Lock()
	mock.calls.ReportBatch = append(mock.calls.ReportBatch, callInfo)
	mock.lockReportBatch.Unlock()
	return mock.ReportBatchFunc(ms)
}

// ReportBatchCalls gets all the calls that were made to ReportBatch.
// Check the length with:
//
//	len(mockedReporter.ReportBatchCalls())
func (mock *ReporterMock) ReportBatchCalls() []struct {
	Ms []*reporter.Metric
} {
	var calls []struct {
		Ms []*reporter.Metric
	}
	mock.lockReportBatch.RLock()
	calls = mock.calls.ReportBatch
	mock.lockReportBatch.RUnlock()
	return calls
}

// ReportOnce calls ReportOnceFunc.
func (mock *ReporterMock) ReportOnce(m *reporter.Metric) error {
	if mock.ReportOnceFunc == nil {
		panic("ReporterMock.ReportOnceFunc: method is nil but Reporter.ReportOnce was just called")
	}
	callInfo := struct {
		M *reporter.Metric
	}{
		M: m,
	}
	mock.lockReportOnce.Lock()
	mock.calls.ReportOnce = append(mock.calls.ReportOnce, callInfo)
	mock.lockReportOnce.Unlock()
	return mock.ReportOnceFunc(m)
}

// ReportOnceCalls gets all the calls that were made to ReportOnce.
// Check the length with:
//
//	len(mockedReporter.ReportOnceCalls())
func (mock *ReporterMock) ReportOnceCalls() []struct {
	M *reporter.Metric
} {
	var calls []struct {
		M *reporter.Metric
	}
	mock.lockReportOnce.RLock()
	calls = mock.calls.ReportOnce
	mock.lockReportOnce.RUnlock()
	return calls
}
