// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/nkiryanov/go-metrics/internal/storage"
)

// StorableParserMock is a mock implementation of storage.StorableParser.
//
//	func TestSomethingThatUsesStorableParser(t *testing.T) {
//
//		// make and configure a mocked storage.StorableParser
//		mockedStorableParser := &StorableParserMock{
//			ParseFunc: func(mType string, s string) (storage.Storable, error) {
//				panic("mock out the Parse method")
//			},
//			ParseCounterFunc: func(s string) (storage.Counter, error) {
//				panic("mock out the ParseCounter method")
//			},
//			ParseGaugeFunc: func(s string) (storage.Gauge, error) {
//				panic("mock out the ParseGauge method")
//			},
//		}
//
//		// use mockedStorableParser in code that requires storage.StorableParser
//		// and then make assertions.
//
//	}
type StorableParserMock struct {
	// ParseFunc mocks the Parse method.
	ParseFunc func(mType string, s string) (storage.Storable, error)

	// ParseCounterFunc mocks the ParseCounter method.
	ParseCounterFunc func(s string) (storage.Counter, error)

	// ParseGaugeFunc mocks the ParseGauge method.
	ParseGaugeFunc func(s string) (storage.Gauge, error)

	// calls tracks calls to the methods.
	calls struct {
		// Parse holds details about calls to the Parse method.
		Parse []struct {
			// MType is the mType argument value.
			MType string
			// S is the s argument value.
			S string
		}
		// ParseCounter holds details about calls to the ParseCounter method.
		ParseCounter []struct {
			// S is the s argument value.
			S string
		}
		// ParseGauge holds details about calls to the ParseGauge method.
		ParseGauge []struct {
			// S is the s argument value.
			S string
		}
	}
	lockParse        sync.RWMutex
	lockParseCounter sync.RWMutex
	lockParseGauge   sync.RWMutex
}

// Parse calls ParseFunc.
func (mock *StorableParserMock) Parse(mType string, s string) (storage.Storable, error) {
	if mock.ParseFunc == nil {
		panic("StorableParserMock.ParseFunc: method is nil but StorableParser.Parse was just called")
	}
	callInfo := struct {
		MType string
		S     string
	}{
		MType: mType,
		S:     s,
	}
	mock.lockParse.Lock()
	mock.calls.Parse = append(mock.calls.Parse, callInfo)
	mock.lockParse.Unlock()
	return mock.ParseFunc(mType, s)
}

// ParseCalls gets all the calls that were made to Parse.
// Check the length with:
//
//	len(mockedStorableParser.ParseCalls())
func (mock *StorableParserMock) ParseCalls() []struct {
	MType string
	S     string
} {
	var calls []struct {
		MType string
		S     string
	}
	mock.lockParse.RLock()
	calls = mock.calls.Parse
	mock.lockParse.RUnlock()
	return calls
}

// ParseCounter calls ParseCounterFunc.
func (mock *StorableParserMock) ParseCounter(s string) (storage.Counter, error) {
	if mock.ParseCounterFunc == nil {
		panic("StorableParserMock.ParseCounterFunc: method is nil but StorableParser.ParseCounter was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockParseCounter.Lock()
	mock.calls.ParseCounter = append(mock.calls.ParseCounter, callInfo)
	mock.lockParseCounter.Unlock()
	return mock.ParseCounterFunc(s)
}

// ParseCounterCalls gets all the calls that were made to ParseCounter.
// Check the length with:
//
//	len(mockedStorableParser.ParseCounterCalls())
func (mock *StorableParserMock) ParseCounterCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockParseCounter.RLock()
	calls = mock.calls.ParseCounter
	mock.lockParseCounter.RUnlock()
	return calls
}

// ParseGauge calls ParseGaugeFunc.
func (mock *StorableParserMock) ParseGauge(s string) (storage.Gauge, error) {
	if mock.ParseGaugeFunc == nil {
		panic("StorableParserMock.ParseGaugeFunc: method is nil but StorableParser.ParseGauge was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockParseGauge.Lock()
	mock.calls.ParseGauge = append(mock.calls.ParseGauge, callInfo)
	mock.lockParseGauge.Unlock()
	return mock.ParseGaugeFunc(s)
}

// ParseGaugeCalls gets all the calls that were made to ParseGauge.
// Check the length with:
//
//	len(mockedStorableParser.ParseGaugeCalls())
func (mock *StorableParserMock) ParseGaugeCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockParseGauge.RLock()
	calls = mock.calls.ParseGauge
	mock.lockParseGauge.RUnlock()
	return calls
}
