// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/nkiryanov/go-metrics/internal/storage"
)

// StorableParserMock is a mock implementation of storage.StorableParser.
//
//	func TestSomethingThatUsesStorableParser(t *testing.T) {
//
//		// make and configure a mocked storage.StorableParser
//		mockedStorableParser := &StorableParserMock{
//			ParseFunc: func(mType string, s string) (storage.Storable, error) {
//				panic("mock out the Parse method")
//			},
//		}
//
//		// use mockedStorableParser in code that requires storage.StorableParser
//		// and then make assertions.
//
//	}
type StorableParserMock struct {
	// ParseFunc mocks the Parse method.
	ParseFunc func(mType string, s string) (storage.Storable, error)

	// calls tracks calls to the methods.
	calls struct {
		// Parse holds details about calls to the Parse method.
		Parse []struct {
			// MType is the mType argument value.
			MType string
			// S is the s argument value.
			S string
		}
	}
	lockParse sync.RWMutex
}

// Parse calls ParseFunc.
func (mock *StorableParserMock) Parse(mType string, s string) (storage.Storable, error) {
	if mock.ParseFunc == nil {
		panic("StorableParserMock.ParseFunc: method is nil but StorableParser.Parse was just called")
	}
	callInfo := struct {
		MType string
		S     string
	}{
		MType: mType,
		S:     s,
	}
	mock.lockParse.Lock()
	mock.calls.Parse = append(mock.calls.Parse, callInfo)
	mock.lockParse.Unlock()
	return mock.ParseFunc(mType, s)
}

// ParseCalls gets all the calls that were made to Parse.
// Check the length with:
//
//	len(mockedStorableParser.ParseCalls())
func (mock *StorableParserMock) ParseCalls() []struct {
	MType string
	S     string
} {
	var calls []struct {
		MType string
		S     string
	}
	mock.lockParse.RLock()
	calls = mock.calls.Parse
	mock.lockParse.RUnlock()
	return calls
}
