// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/nkiryanov/go-metrics/internal/models"
)

// StorageMock is a mock implementation of storage.Storage.
//
//	func TestSomethingThatUsesStorage(t *testing.T) {
//
//		// make and configure a mocked storage.Storage
//		mockedStorage := &StorageMock{
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			CountMetricFunc: func(ctx context.Context) (int, error) {
//				panic("mock out the CountMetric method")
//			},
//			GetMetricFunc: func(ctx context.Context, mType string, mName string) (models.Metric, error) {
//				panic("mock out the GetMetric method")
//			},
//			ListMetricFunc: func(ctx context.Context) ([]models.Metric, error) {
//				panic("mock out the ListMetric method")
//			},
//			PingFunc: func(ctx context.Context) error {
//				panic("mock out the Ping method")
//			},
//			UpdateMetricFunc: func(ctx context.Context, in *models.Metric) (models.Metric, error) {
//				panic("mock out the UpdateMetric method")
//			},
//			UpdateMetricBulkFunc: func(ctx context.Context, metrics []models.Metric) ([]models.Metric, error) {
//				panic("mock out the UpdateMetricBulk method")
//			},
//		}
//
//		// use mockedStorage in code that requires storage.Storage
//		// and then make assertions.
//
//	}
type StorageMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// CountMetricFunc mocks the CountMetric method.
	CountMetricFunc func(ctx context.Context) (int, error)

	// GetMetricFunc mocks the GetMetric method.
	GetMetricFunc func(ctx context.Context, mType string, mName string) (models.Metric, error)

	// ListMetricFunc mocks the ListMetric method.
	ListMetricFunc func(ctx context.Context) ([]models.Metric, error)

	// PingFunc mocks the Ping method.
	PingFunc func(ctx context.Context) error

	// UpdateMetricFunc mocks the UpdateMetric method.
	UpdateMetricFunc func(ctx context.Context, in *models.Metric) (models.Metric, error)

	// UpdateMetricBulkFunc mocks the UpdateMetricBulk method.
	UpdateMetricBulkFunc func(ctx context.Context, metrics []models.Metric) ([]models.Metric, error)

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// CountMetric holds details about calls to the CountMetric method.
		CountMetric []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetMetric holds details about calls to the GetMetric method.
		GetMetric []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// MType is the mType argument value.
			MType string
			// MName is the mName argument value.
			MName string
		}
		// ListMetric holds details about calls to the ListMetric method.
		ListMetric []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Ping holds details about calls to the Ping method.
		Ping []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// UpdateMetric holds details about calls to the UpdateMetric method.
		UpdateMetric []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *models.Metric
		}
		// UpdateMetricBulk holds details about calls to the UpdateMetricBulk method.
		UpdateMetricBulk []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Metrics is the metrics argument value.
			Metrics []models.Metric
		}
	}
	lockClose            sync.RWMutex
	lockCountMetric      sync.RWMutex
	lockGetMetric        sync.RWMutex
	lockListMetric       sync.RWMutex
	lockPing             sync.RWMutex
	lockUpdateMetric     sync.RWMutex
	lockUpdateMetricBulk sync.RWMutex
}

// Close calls CloseFunc.
func (mock *StorageMock) Close() error {
	if mock.CloseFunc == nil {
		panic("StorageMock.CloseFunc: method is nil but Storage.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedStorage.CloseCalls())
func (mock *StorageMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// CountMetric calls CountMetricFunc.
func (mock *StorageMock) CountMetric(ctx context.Context) (int, error) {
	if mock.CountMetricFunc == nil {
		panic("StorageMock.CountMetricFunc: method is nil but Storage.CountMetric was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCountMetric.Lock()
	mock.calls.CountMetric = append(mock.calls.CountMetric, callInfo)
	mock.lockCountMetric.Unlock()
	return mock.CountMetricFunc(ctx)
}

// CountMetricCalls gets all the calls that were made to CountMetric.
// Check the length with:
//
//	len(mockedStorage.CountMetricCalls())
func (mock *StorageMock) CountMetricCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCountMetric.RLock()
	calls = mock.calls.CountMetric
	mock.lockCountMetric.RUnlock()
	return calls
}

// GetMetric calls GetMetricFunc.
func (mock *StorageMock) GetMetric(ctx context.Context, mType string, mName string) (models.Metric, error) {
	if mock.GetMetricFunc == nil {
		panic("StorageMock.GetMetricFunc: method is nil but Storage.GetMetric was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		MType string
		MName string
	}{
		Ctx:   ctx,
		MType: mType,
		MName: mName,
	}
	mock.lockGetMetric.Lock()
	mock.calls.GetMetric = append(mock.calls.GetMetric, callInfo)
	mock.lockGetMetric.Unlock()
	return mock.GetMetricFunc(ctx, mType, mName)
}

// GetMetricCalls gets all the calls that were made to GetMetric.
// Check the length with:
//
//	len(mockedStorage.GetMetricCalls())
func (mock *StorageMock) GetMetricCalls() []struct {
	Ctx   context.Context
	MType string
	MName string
} {
	var calls []struct {
		Ctx   context.Context
		MType string
		MName string
	}
	mock.lockGetMetric.RLock()
	calls = mock.calls.GetMetric
	mock.lockGetMetric.RUnlock()
	return calls
}

// ListMetric calls ListMetricFunc.
func (mock *StorageMock) ListMetric(ctx context.Context) ([]models.Metric, error) {
	if mock.ListMetricFunc == nil {
		panic("StorageMock.ListMetricFunc: method is nil but Storage.ListMetric was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListMetric.Lock()
	mock.calls.ListMetric = append(mock.calls.ListMetric, callInfo)
	mock.lockListMetric.Unlock()
	return mock.ListMetricFunc(ctx)
}

// ListMetricCalls gets all the calls that were made to ListMetric.
// Check the length with:
//
//	len(mockedStorage.ListMetricCalls())
func (mock *StorageMock) ListMetricCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListMetric.RLock()
	calls = mock.calls.ListMetric
	mock.lockListMetric.RUnlock()
	return calls
}

// Ping calls PingFunc.
func (mock *StorageMock) Ping(ctx context.Context) error {
	if mock.PingFunc == nil {
		panic("StorageMock.PingFunc: method is nil but Storage.Ping was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockPing.Lock()
	mock.calls.Ping = append(mock.calls.Ping, callInfo)
	mock.lockPing.Unlock()
	return mock.PingFunc(ctx)
}

// PingCalls gets all the calls that were made to Ping.
// Check the length with:
//
//	len(mockedStorage.PingCalls())
func (mock *StorageMock) PingCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockPing.RLock()
	calls = mock.calls.Ping
	mock.lockPing.RUnlock()
	return calls
}

// UpdateMetric calls UpdateMetricFunc.
func (mock *StorageMock) UpdateMetric(ctx context.Context, in *models.Metric) (models.Metric, error) {
	if mock.UpdateMetricFunc == nil {
		panic("StorageMock.UpdateMetricFunc: method is nil but Storage.UpdateMetric was just called")
	}
	callInfo := struct {
		Ctx context.Context
		In  *models.Metric
	}{
		Ctx: ctx,
		In:  in,
	}
	mock.lockUpdateMetric.Lock()
	mock.calls.UpdateMetric = append(mock.calls.UpdateMetric, callInfo)
	mock.lockUpdateMetric.Unlock()
	return mock.UpdateMetricFunc(ctx, in)
}

// UpdateMetricCalls gets all the calls that were made to UpdateMetric.
// Check the length with:
//
//	len(mockedStorage.UpdateMetricCalls())
func (mock *StorageMock) UpdateMetricCalls() []struct {
	Ctx context.Context
	In  *models.Metric
} {
	var calls []struct {
		Ctx context.Context
		In  *models.Metric
	}
	mock.lockUpdateMetric.RLock()
	calls = mock.calls.UpdateMetric
	mock.lockUpdateMetric.RUnlock()
	return calls
}

// UpdateMetricBulk calls UpdateMetricBulkFunc.
func (mock *StorageMock) UpdateMetricBulk(ctx context.Context, metrics []models.Metric) ([]models.Metric, error) {
	if mock.UpdateMetricBulkFunc == nil {
		panic("StorageMock.UpdateMetricBulkFunc: method is nil but Storage.UpdateMetricBulk was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Metrics []models.Metric
	}{
		Ctx:     ctx,
		Metrics: metrics,
	}
	mock.lockUpdateMetricBulk.Lock()
	mock.calls.UpdateMetricBulk = append(mock.calls.UpdateMetricBulk, callInfo)
	mock.lockUpdateMetricBulk.Unlock()
	return mock.UpdateMetricBulkFunc(ctx, metrics)
}

// UpdateMetricBulkCalls gets all the calls that were made to UpdateMetricBulk.
// Check the length with:
//
//	len(mockedStorage.UpdateMetricBulkCalls())
func (mock *StorageMock) UpdateMetricBulkCalls() []struct {
	Ctx     context.Context
	Metrics []models.Metric
} {
	var calls []struct {
		Ctx     context.Context
		Metrics []models.Metric
	}
	mock.lockUpdateMetricBulk.RLock()
	calls = mock.calls.UpdateMetricBulk
	mock.lockUpdateMetricBulk.RUnlock()
	return calls
}
