// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/nkiryanov/go-metrics/internal/models"
)

// StorageMock is a mock implementation of storage.Storage.
//
//	func TestSomethingThatUsesStorage(t *testing.T) {
//
//		// make and configure a mocked storage.Storage
//		mockedStorage := &StorageMock{
//			CountMetricFunc: func() int {
//				panic("mock out the CountMetric method")
//			},
//			GetMetricFunc: func(mType string, mName string) (models.Metric, error) {
//				panic("mock out the GetMetric method")
//			},
//			ListMetricFunc: func() ([]models.Metric, error) {
//				panic("mock out the ListMetric method")
//			},
//			UpdateMetricFunc: func(in *models.Metric) (models.Metric, error) {
//				panic("mock out the UpdateMetric method")
//			},
//		}
//
//		// use mockedStorage in code that requires storage.Storage
//		// and then make assertions.
//
//	}
type StorageMock struct {
	// CountMetricFunc mocks the CountMetric method.
	CountMetricFunc func() int

	// GetMetricFunc mocks the GetMetric method.
	GetMetricFunc func(mType string, mName string) (models.Metric, error)

	// ListMetricFunc mocks the ListMetric method.
	ListMetricFunc func() ([]models.Metric, error)

	// UpdateMetricFunc mocks the UpdateMetric method.
	UpdateMetricFunc func(in *models.Metric) (models.Metric, error)

	// calls tracks calls to the methods.
	calls struct {
		// CountMetric holds details about calls to the CountMetric method.
		CountMetric []struct {
		}
		// GetMetric holds details about calls to the GetMetric method.
		GetMetric []struct {
			// MType is the mType argument value.
			MType string
			// MName is the mName argument value.
			MName string
		}
		// ListMetric holds details about calls to the ListMetric method.
		ListMetric []struct {
		}
		// UpdateMetric holds details about calls to the UpdateMetric method.
		UpdateMetric []struct {
			// In is the in argument value.
			In *models.Metric
		}
	}
	lockCountMetric  sync.RWMutex
	lockGetMetric    sync.RWMutex
	lockListMetric   sync.RWMutex
	lockUpdateMetric sync.RWMutex
}

// CountMetric calls CountMetricFunc.
func (mock *StorageMock) CountMetric() int {
	if mock.CountMetricFunc == nil {
		panic("StorageMock.CountMetricFunc: method is nil but Storage.CountMetric was just called")
	}
	callInfo := struct {
	}{}
	mock.lockCountMetric.Lock()
	mock.calls.CountMetric = append(mock.calls.CountMetric, callInfo)
	mock.lockCountMetric.Unlock()
	return mock.CountMetricFunc()
}

// CountMetricCalls gets all the calls that were made to CountMetric.
// Check the length with:
//
//	len(mockedStorage.CountMetricCalls())
func (mock *StorageMock) CountMetricCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCountMetric.RLock()
	calls = mock.calls.CountMetric
	mock.lockCountMetric.RUnlock()
	return calls
}

// GetMetric calls GetMetricFunc.
func (mock *StorageMock) GetMetric(mType string, mName string) (models.Metric, error) {
	if mock.GetMetricFunc == nil {
		panic("StorageMock.GetMetricFunc: method is nil but Storage.GetMetric was just called")
	}
	callInfo := struct {
		MType string
		MName string
	}{
		MType: mType,
		MName: mName,
	}
	mock.lockGetMetric.Lock()
	mock.calls.GetMetric = append(mock.calls.GetMetric, callInfo)
	mock.lockGetMetric.Unlock()
	return mock.GetMetricFunc(mType, mName)
}

// GetMetricCalls gets all the calls that were made to GetMetric.
// Check the length with:
//
//	len(mockedStorage.GetMetricCalls())
func (mock *StorageMock) GetMetricCalls() []struct {
	MType string
	MName string
} {
	var calls []struct {
		MType string
		MName string
	}
	mock.lockGetMetric.RLock()
	calls = mock.calls.GetMetric
	mock.lockGetMetric.RUnlock()
	return calls
}

// ListMetric calls ListMetricFunc.
func (mock *StorageMock) ListMetric() ([]models.Metric, error) {
	if mock.ListMetricFunc == nil {
		panic("StorageMock.ListMetricFunc: method is nil but Storage.ListMetric was just called")
	}
	callInfo := struct {
	}{}
	mock.lockListMetric.Lock()
	mock.calls.ListMetric = append(mock.calls.ListMetric, callInfo)
	mock.lockListMetric.Unlock()
	return mock.ListMetricFunc()
}

// ListMetricCalls gets all the calls that were made to ListMetric.
// Check the length with:
//
//	len(mockedStorage.ListMetricCalls())
func (mock *StorageMock) ListMetricCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockListMetric.RLock()
	calls = mock.calls.ListMetric
	mock.lockListMetric.RUnlock()
	return calls
}

// UpdateMetric calls UpdateMetricFunc.
func (mock *StorageMock) UpdateMetric(in *models.Metric) (models.Metric, error) {
	if mock.UpdateMetricFunc == nil {
		panic("StorageMock.UpdateMetricFunc: method is nil but Storage.UpdateMetric was just called")
	}
	callInfo := struct {
		In *models.Metric
	}{
		In: in,
	}
	mock.lockUpdateMetric.Lock()
	mock.calls.UpdateMetric = append(mock.calls.UpdateMetric, callInfo)
	mock.lockUpdateMetric.Unlock()
	return mock.UpdateMetricFunc(in)
}

// UpdateMetricCalls gets all the calls that were made to UpdateMetric.
// Check the length with:
//
//	len(mockedStorage.UpdateMetricCalls())
func (mock *StorageMock) UpdateMetricCalls() []struct {
	In *models.Metric
} {
	var calls []struct {
		In *models.Metric
	}
	mock.lockUpdateMetric.RLock()
	calls = mock.calls.UpdateMetric
	mock.lockUpdateMetric.RUnlock()
	return calls
}
